config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", registrations: 'users/registrations' }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root 'home#index'

  resources :books
  resources :addresses
  resources :categories do
    resources :books, :index
  end
  resources :line_items
  resources :orders
  resources :reviews
  resources :settings
  resources :settings_emails
  resource :account
  resources :coupons
  resources :checkout, param: :step
  resources :carts, path: '/carts/line_items'
end

app/models/address.rb
class Address < ApplicationRecord
  enum address_type: { billing: 0, shipping: 1 }

  belongs_to :resource, polymorphic: true
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :book_authors, dependent: :destroy
  has_many :books, through: :book_authors, dependent: nil

  def full_name
    "#{first_name}' '#{last_name}"
  end
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :category
  has_many :book_authors, dependent: :destroy
  has_many :authors, through: :book_authors, dependent: nil
  has_many :reviews, dependent: :destroy
  has_many :line_items, dependent: :destroy
  has_many :book_images, dependent: :destroy
end

app/models/book_author.rb
class BookAuthor < ApplicationRecord
  belongs_to :book
  belongs_to :author
end

app/models/book_image.rb
class BookImage < ApplicationRecord
  include ImageUploader::Attachment(:image)
  enum image_type: { main: 0, additional: 1 }

  belongs_to :book, optional: true

  validate :main_image

  private

  def main_image
    return unless book
    return unless book.book_images.main.present? && image_type == 'main'

    errors.add :image_type, I18n.t('validate.main_image')
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :books, dependent: :destroy
end

app/models/coupon.rb
class Coupon < ApplicationRecord
  belongs_to :order, optional: true
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  belongs_to :order
end

app/models/delivery.rb
class Delivery < ApplicationRecord
  has_many :orders, dependent: :destroy
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :book
  belongs_to :order, optional: true
end

app/models/order.rb
class Order < ApplicationRecord
  include AASM

  belongs_to :delivery, optional: true
  belongs_to :user, optional: true
  has_many :line_items, dependent: :destroy
  has_many :books, through: :line_items
  has_many :addresses, as: :resource, dependent: :destroy
  has_one :credit_card, dependent: :destroy
  has_one :coupon, dependent: :nullify

  scope :in_progress, -> { Order.complete }
  scope :in_delivery, -> { Order.in_delivery }
  scope :delivered, -> { Order.delivered }
  scope :canceled, -> { Order.canceled }

  enum status: { cart: 0, address: 1, fill_delivery: 2, payment: 3, confirm: 4, complete: 5,
                 in_delivery: 6, delivered: 7, canceled: 8 }

  aasm :status, enum: true do
    state :cart, initial: true
    state :address
    state :fill_delivery
    state :payment
    state :confirm
    state :complete
    state :in_delivery
    state :delivered
    state :canceled

    event :address do
      transitions from: :cart, to: :address
    end

    event :fill_delivery do
      transitions from: :address, to: :fill_delivery
    end

    event :payment do
      transitions from: :fill_delivery, to: :payment
    end

    event :confirm do
      transitions from: :payment, to: :confirm
    end

    event :complete do
      transitions from: :confirm, to: :complete
    end

    event :in_delivery do
      transitions from: :complete, to: :in_delivery
    end

    event :delivered do
      transitions from: :in_delivery, to: :delivered
    end

    event :canceled do
      transitions from: %i[complete in_delivery delivered], to: :canceled
    end
  end
end

app/models/review.rb
class Review < ApplicationRecord
  enum status: { unprocessed: 0, approved: 1, rejected: 2 }

  belongs_to :user
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :orders, dependent: nil
  has_many :addresses, as: :resource, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :confirmable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook]

  validate :password_complexity

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.skip_confirmation!
    end
  end

  def password_complexity
    return if password.blank? || password =~ /(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])/

    errors.add :password, I18n.t('validate.password_complexity')
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  include Pagy::Backend

  COUNT_PAGE_BOOKS = 12

  def index
    @sorted_books = SortingService.new(Book.all, params).call
    @books_presenter = BooksPresenter.new(params: params)
    @pagy, @books_category = pagy(@sorted_books, items: COUNT_PAGE_BOOKS)
  end

  def show
    @current_book = Book.find_by(id: params[:id])
    @review_presenter = ReviewPresenter.new(current_book: @current_book)
    @current_book_presenter = CurrentBookPresenter.new(current_book: @current_book)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def index
    @books_presenter = BooksPresenter.new(params: params)
    @cart_presenter = CartPresenter.new(current_order: current_order)
    @cart_books = current_order&.books
  end
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  after_action :clear_order_session, only: [:show]

  def show
    service = CheckoutShowService.new(params, current_order, current_user)
    return redirect_to(carts_path) unless current_order
    return redirect_to(step: current_order.status) unless service.current_presenter

    @cart_presenter = CartPresenter.new(current_order: current_order)
    @presenter = service.current_presenter
  end

  def update
    service = CheckoutUpdateService.new(params.permit!, current_order, current_user)
    return redirect_to checkout_path(step: service.go_to_next_step) if service.call

    @cart_presenter = service.cart_presenter
    @presenter = service.presenter
    render :show
  end

  private

  def clear_order_session
    cookies.delete(:current_order_id) if current_order&.complete?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @books_presenter = BooksPresenter.new(params: params)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!

  def index
    @sort_orders = OrderSortingService.new(params, current_user).call
  end

  def show
    find_order = Order.find_by(id: params[:id])
    return redirect_to orders_path unless find_order

    @order = find_order.decorate
    @cart_presenter = CartPresenter.new(current_order: @order)
  end
end

app/helpers/books_helper.rb
module BooksHelper
  include Pagy::Frontend
end

app/helpers/checkout_helper.rb
module CheckoutHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def resource_class
    devise_mapping.to
  end
end

app/views/checkout/_address.html.haml
%main.container
  = render partial: 'checkout/points_steps/types_steps'
  = form_for @presenter.billing, url: checkout_path, method: :put, class: 'res-mb-100' do |form|
    .row
      .col-md-5
        %h3.general-subtitle
          = t('checkout.billing_address')
        %p.general-info-text
          = t('checkout.all_fields_required')
        = fields_for :billing_form, @presenter.billing do |f|
          = render partial: 'addresses/inputs_form', locals: {f: f,address_form: @presenter.billing, address_type: 'billing', order_form: true}
      .col-md-5.col-md-offset-1
        %h3.general-subtitle
          = t('checkout.shippint_address')
        %p.general-info-text.invisible
          = t('checkout.all_fields_required')
        %div.shipping-form
          = fields_for :shipping_form, @presenter.shipping do |f|
            = render partial: 'addresses/inputs_form', locals: {f: f, address_form: @presenter.shipping, address_type: 'shipping', order_form: true}
        .form-group.checkbox
          %label.checkbox-label
            %input.checkbox-input.check-box-shipping{type: "checkbox", hidden: "true", name: 'hidden_shipping_form', id: 'hide_shipping_form'}
            %span.checkbox-icon
              %i.fa.fa-check
            %span.checkbox-text
              = t('checkout.use_billing_address')
    .general-text-align.mb-60
      = render partial: 'checkout/order_summary/order_price'
      = form.submit t('checkout.save_and_continue'), class: 'btn center-block mb-20'

app/views/checkout/_complete.html.haml
%main.container.general-main-wrap
  = render partial: 'checkout/points_steps/types_steps'
  .text-center.mb-40
    %h3.general-subtitle
      = t('checkout.thank_for_order')
    %p.fw-300
      = t('checkout.send_massage_email_in_complete', email: @presenter.current_order.user.email)
  .row.mb-20
    .col-sm-6
      .visible-xs
        %p.general-order-number.mb-0
          = t('checkout.order_number_complete', number: @presenter.current_order.number)
        %p.general-address.mb-30
          = @presenter.current_order.created_at.to_date
      - @presenter.current_order.addresses.shipping.each do |address|
        %p.general-address
          = address.first_name
          = address.last_name
          %br
          = address.address
          %br
          = address.city
          %br
          = address.country
          %br
          = t('checkout.phone_complete', phone: address.phone)
    .col-sm-6.hidden-xs.text-right
      %p.general-order-number.mb-0
        = t('checkout.order_number_complete', number: @presenter.current_order.number)
      %p.general-address.mb-30
        = @presenter.current_order.created_at.to_date
  .visible-xs
    - @presenter.current_order.line_items.each do |item|
      .general-cart-item.divider-lg
        .general-img-wrap-table
          %img.cart-img-shadow{src: @presenter.main_image_or_default(item.book), alt: "design-book"}
        %p.title
          = item.book.title
        %P.in-grey-600.fw-300
          = item.book.description
        %table.table
          %tr
            %td
              %span.in-grey-600
                = t('checkout.price')
            %td
              %span.font-16.in-gold-500
                = "€#{item.book.price}"
          %tr
            %td.vertical-middle
              %span.in-grey-600
                = t('checkout.quantity')
            %td
              %span
                = item.quantity
          %tr
            %td
              %span.in-grey-600
                = t('checkout.subtotal')
            %td
              %span.font-16.in-gold-500
                = "€#{@cart_presenter.order_summary_price}"
  .hidden-xs.divider-lg.pt-20
    %table.table.table-hover
      %thead
        %tr
          %th
            %span.in-grey-600
              = t('checkout.book')
          %th.col-method
          %th
            %span.in-grey-600
              = t('checkout.price')
          %th
            %span.in-grey-600
              = t('checkout.quantity')
          %th
            %span.in-grey-600
              = t('checkout.total')
      %tbody
        - @presenter.current_order.line_items.each do |item|
          %tr
            %td
              .general-img-wrap-table
                %img.cart-img-shadow{src: @presenter.main_image_or_default(item.book), alt: "design-book"}
            %td
              %p.title
                = item.book.title
              %p.in-grey-600.fw-300
                = item.book.description
            %td
              %span.font-16.in-gold-500
                = "€#{item.book.price}"
            %td
              %span.ml-30
                = item.quantity
            %td
              %span.font-16.in-gold-500
                = "€#{@cart_presenter.order_summary_price}"
  %row
    .text-center.general-text-right.col-sm-12.col-md-12.col-xs-12.confirm-subtotal-price
      = render partial: 'checkout/order_summary/order_price'
  .text-center
    = link_to 'Back to Store', root_path, class: 'btn btn-default mb-20'

app/views/checkout/_confirm.html.haml
%main.container.general-main-wrap
  = render partial: 'checkout/points_steps/types_steps'
  .row.mb-20
    .col-sm-3
      %h3.general-subtitle
        = t('checkout.shippint_address')
      - @presenter.current_order.addresses.shipping.each do |address|
        = render partial: 'checkout/info_confirm/addresses_checkout', locals: {address: address}
    .col-sm-3
      %h3.general-subtitle
        = t('checkout.billing_address')
      - @presenter.current_order.addresses.billing.each do |address|
        = render partial: 'checkout/info_confirm/addresses_checkout', locals: {address: address}
    .col-sm-3
      %h3.general-subtitle
        = t('checkout.shipments')
      %p.general-address
        = @presenter.current_order.delivery.method
        %a.general-edit.step-delivery{href: '/checkout/fill_delivery'}
          = t('checkout.edit')
    .col-sm-3
      %h3.general-subtitle
        = t('checkout.payment_information')
      %p.general-address
        = ConfirmPresenter::SECRET_NUMS_FOR_CARD + @presenter.lash_four_nums_card
        %a.general-edit.step-payment{href: '/checkout/payment'}
          = t('checkout.edit')
        %br
        = @presenter.current_order.credit_card.date
  .visible-xs
    = render partial: 'checkout/info_confirm/line_items_phone'
  .hidden-xs.divider-lg.pt-20
    %table.table.table-hover
      %thead
        %tr
          %th
            %span.in-grey-600
              = t('checkout.book')
          %th.col-method
          %th
            %span.in-grey-600
              = t('checkout.price')
          %th
            %span.in-grey-600
              = t('checkout.quantity')
          %th
            %span.in-grey-600
              = t('checkout.total')
      %tbody
        - @presenter.current_order.line_items.each do |item|
          %tr
            %td
              .general-img-wrap-table
                %img.cart-img-shadow.pull-left{src: @presenter.main_image_or_default(item.book), alt: "design-book"}
            %td
              %p.title
                = item.book.title
              %p.in-grey-600.fw-300
                = item.book.description
            %td
              %span.font-16.in-gold-500
                = I18n.t('checkout.item_book_price', price: item.book.price)
            %td
              %span.ml-30
                = item.quantity
            %td
              %span.font-16.in-gold-500
                = I18n.t('checkout.item_book_price', price: @cart_presenter.subtotal_prise_book(item.book))
  %row
    .text-center.general-text-right.col-sm-12.col-md-12.col-xs-12.confirm-subtotal-price
      = render partial: 'checkout/order_summary/order_price'
    = form_tag checkout_path, method: :put do
      .text-center
        = submit_tag 'Place Order', class: 'btn btn-default mb-20'

app/views/checkout/_fill_delivery.html.haml
%main.container.general-main-wrap
  = render partial: 'checkout/points_steps/types_steps'
  %h3.general-subtitle
    = t('checkout.delivery_title')
  = render partial: 'checkout/delivery_forms/for_phone'
  = form_tag checkout_path, method: :put do
    .hidden-xs.mb-res-50
      %table.table.table-hover
        %thead
          %tr
            %th.col-method
              %span.in-grey-600.ml-40
                = t('checkout.method')
            %th
              %span.in-grey-600
                = t('checkout.days')
            %th
              %span.in-grey-600
                = t('checkout.price')
        %tbody
          - Delivery.all.each_with_index do |delivery, index|
            %tr
              %td
                .form-group.radio.mt-0.mb-0
                  %label.radio-label
                    = radio_button_tag :delivery_id, delivery.id, @presenter.check_exists_delivery(delivery.id) || index.zero?, class: 'radio-input', hidden: true
                    %span.radio-icon
                    %span.radio-text
                      = delivery.method
              %td
                %span
                  = "from #{delivery.from_days} to #{delivery.to_days} days"
              %td
                %span.font-16.in-gold-500
                  = "€#{delivery.price}"
    .general-text-align
      = render partial: 'checkout/order_summary/order_price'
    .text-center
      = submit_tag t('checkout.save_and_continue'), class: 'btn btn-default mb-20'

app/views/checkout/_payment.html.haml
%main.container.mb-res-50
  = render partial: 'checkout/points_steps/types_steps'
  %h3.general-subtitle
    = t('checkout.credit_card_title')
  = simple_form_for(@presenter.payment_card, url: checkout_path, validate: true, method: :put, html: { class: 'max-600 mb-80 field_with_errors' },
    defaults: { input_html: { class: 'form-control' }, label_html: { class: 'control-label input-label' } }) do |f|
    .form-group
      = f.input :order_id, as: :hidden, input_html: { value: @presenter.current_order.id }
      = f.input :number, label: t('checkout.card_number'), placeholder: t('checkout.card_number')
    .row
      .col-sm-6
        .form-group
          = f.input :name, label: t('checkout.name_on_card'), placeholder: t('checkout.name_on_card')
      .col-sm-3
        .form-group
          = f.input :date, label: t('checkout.mm_yy'), placeholder: t('checkout.mm_yy')
      .col-sm-3
        .form-group.relative
          = f.input :cvv, as: :password, label: t('checkout.cvv'), placeholder: t('checkout.cvv'), type: 'password'
          %span.cvv-hint
            %i.fa.fa-question-circle.general-form-help
            %span.cvv-hint-text
              = t('checkout.cvv_hint')
    .general-text-align.mt-50
      = render partial: 'checkout/order_summary/order_price'
    .text-center
      = f.button :submit, t('checkout.save_and_continue'), class: 'btn btn-default mb-80'

app/views/checkout/_quick_registrate.html.haml
%main.container
  .row
    .col-md-5.mb-40
      .text-center
        %h3.general-subtitle
          = t('checkout.returning_customer')
        %a.general-login-icon{href: "#"}
          - if devise_mapping.omniauthable?
            - resource_class.omniauth_providers.each do |provider|
              = link_to omniauth_authorize_path(resource_name, provider) do
                %i.fa.fa-facebook-official.facebook-icon
        %p.general-login-text or
        %p.mb-15.text-left
          = t('checkout.login_with_password')
      = form_for(resource, as: resource_name, url: session_path(resource_name)) do |f|
        .mb-40
          .form-group.mb-30
            %label.control-label.input-label{for: "email"}= t('devise.enter_email')
            = f.email_field :email, autofocus: true, id: 'email', class: 'form-control', placeholder: "Enter Email"
          .form-group.mb-30
            %label.control-label.input-label{for: "password"}= t('devise.enter_password')
            = f.password_field :password, id: 'password', class: 'form-control', placeholder: "Password"
            %a.help-block.in-gold-500
              = render "devise/shared/link_forgot_password"
        %button.btn.btn-default.mb-20
          = f.submit t('checkout.login_with_password'), class: 'btn-submit-login-sign-up'
    .col-md-5.col-md-offset-1.mb-60
      .text-center
        %h3.general-subtitle
          = t('checkout.new_customer')
        %a.general-login-icon{href: "#"}
          - if devise_mapping.omniauthable?
            - resource_class.omniauth_providers.each do |provider|
              = link_to omniauth_authorize_path(resource_name, provider) do
                %i.fa.fa-facebook-official.facebook-icon
        %p.general-login-text or
      = form_for(User.new, url: user_registration_path, method: :post) do |f|
        .mb-40
          %p.mb-5
            = t('checkout.quick_registration')
          %p.general-info-text.font-12.mb-20
            = t('checkout.able_to_create_password_late')
          .form-group.mb-30
            %label.control-label.input-label{for: "email"}
              = t('checkout.enter_email')
            = f.email_field :email, autofocus: true, autocomplete: "email", id: 'email', class: 'form-control', placeholder: t('checkout.enter_email')
            = resource.errors.messages[:email].to_sentence
          .form-group.checkbox.mb-30
            %button.btn.btn-default.mb-20
              = hidden_field_tag :checkout_signup
              = f.submit t('checkout.sign_up'), class: 'btn-submit-login-sign-up'
              

app/views/checkout/delivery_forms/_for_phone.html.haml
.visible-xs
  .general-cart-item.divider-lg-bottom
    %table.table
      %tr
        %td.col-half
          %span.in-grey-600
            = t('checkout.method')
        %td.col-half
          .form-group.radio.mt-0.mb-0
            %label.radio-label
              %input.radio-input{type: "radio", hidden: "true"}
              %span.radio-icon
              %span.radio-text
                = t('checkout.delivery_next_day')
      %tr
        %td
          %span.in-grey-600
            = t('checkout.days')
        %td
          %span.font-16.fw-300
            = t('checkout.period_days')
      %tr
        %td
          %span.in-grey-600
            = t('checkout.price')
        %td
          %span.font-16.in-gold-500
            = t('checkout.five_dollars')

app/views/checkout/info_confirm/_addresses_checkout.html.haml
%p.general-address
  = address.first_name
  %a.general-edit.step-address{href: '/checkout/address'}
    = t('checkout.edit')
  %br
  = address.address
  %br
  = address.city
  %br
  = address.country
  %br
  = t('checkout.phone_complete', phone: address.phone)

app/views/checkout/info_confirm/_line_items_phone.html.haml
.general-cart-item.divider-lg
  - @presenter.current_order.line_items.each do |item|
    .general-img-wrap-table
      %img.cart-img-shadow{src: @presenter.main_image_or_default(item.book), alt: "design-book"}
    %p.title
      = item.book.title
    %P.in-grey-600.fw-300
      = item.book.description
    %table.table
      %tr
        %td
          %span.in-grey-600
            = t('checkout.price')
        %td
          %span.font-16.in-gold-500
            = "€#{item.book.price}"
      %tr
        %td.vertical-middle
          %span.in-grey-600
            = t('checkout.quantity')
        %td
          %span
            = item.quantity
      %tr
        %td
          %span.in-grey-600
            = t('checkout.subtotal')
        %td
          %span.font-16.in-gold-500
            = "€#{@cart_presenter.order_summary_price}"

app/views/checkout/order_summary/_order_price.html.haml
%p.in-gold-500.font-18
  = t('cart.order_summary')
%table.general-summary-table
  %tr
    %td
      %p.font-16
        = t('cart.subtotal_order')
    %td
      %p.font-16
        = "€#{@cart_presenter.order_summary_price}"
  %tr
    %td
      %p.font-16
        = t('cart.coupon')
    %td
      %p.font-16
        = "€#{@cart_presenter.coupon_discount}"
  - if @cart_presenter.current_order.delivery_id
    %tr
      %td
        %p.font-16
          = t('checkout.delivery')
      %td
        %p.font-16
          = "€#{@cart_presenter.delivery_price}"
  %tr
    %td
      %strong.font-18
        = t('cart.order_total')
    %td
      %strong.font-18
        = "€#{@cart_presenter.order_total_price_with_coupon}"

app/views/checkout/points_steps/_types_steps.html.haml
%h1.general-title-margin
  = t('checkout.title')
%ul.steps.list-inline
  - Order.statuses.each do |key, value|
    - if key != Order.statuses.keys.first && value <= Order.statuses[:complete]
      %li.step{class: "#{'active' if value <= Order.statuses[@presenter.class::STEP]}"}
        %span.step-number
          = value
        %span.hidden-xs
          %a{href: checkout_path(step: key), class: 'step_checkout step-text'}
            = key.include?('_') ? key.split('_').last.capitalize : key.to_s.capitalize
      %li{class: "#{'step-divider' if value < Order.statuses[:complete]}"}

app/views/checkout/show.html.haml
= render partial: "checkout/#{@presenter.class::STEP}", locals: { presenter: @presenter }