config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", registrations: 'users/registrations' }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root 'home#index'

  resources :books
  resources :addresses
  resources :categories do
    resources :books, :index
  end
  resources :line_items
  resources :orders
  resources :reviews
  resources :settings
  resources :settings_emails
  resource :account
  resources :coupons
  resources :checkout, param: :step
  resources :carts, path: '/carts/line_items'
end

app/models/address.rb
class Address < ApplicationRecord
  enum address_type: { billing: 0, shipping: 1 }

  belongs_to :resource, polymorphic: true
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :book_authors, dependent: :destroy
  has_many :books, through: :book_authors, dependent: nil

  def full_name
    "#{first_name}' '#{last_name}"
  end
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :category
  has_many :book_authors, dependent: :destroy
  has_many :authors, through: :book_authors, dependent: nil
  has_many :reviews, dependent: :destroy
  has_many :line_items, dependent: :destroy
  has_many :book_images, dependent: :destroy
end

app/models/book_author.rb
class BookAuthor < ApplicationRecord
  belongs_to :book
  belongs_to :author
end

app/models/book_image.rb
class BookImage < ApplicationRecord
  include ImageUploader::Attachment(:image)
  enum image_type: { main: 0, additional: 1 }

  belongs_to :book, optional: true

  validate :main_image

  private

  def main_image
    return unless book
    return unless book.book_images.main.present? && image_type == 'main'

    errors.add :image_type, I18n.t('validate.main_image')
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :books, dependent: :destroy
end

app/models/coupon.rb
class Coupon < ApplicationRecord
  belongs_to :order, optional: true
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  belongs_to :order
end

app/models/delivery.rb
class Delivery < ApplicationRecord
  has_many :orders, dependent: :destroy
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :book
  belongs_to :order, optional: true
end

app/models/order.rb
class Order < ApplicationRecord
  include AASM

  belongs_to :delivery, optional: true
  belongs_to :user, optional: true
  has_many :line_items, dependent: :destroy
  has_many :books, through: :line_items
  has_many :addresses, as: :resource, dependent: :destroy
  has_one :credit_card, dependent: :destroy
  has_one :coupon, dependent: :nullify

  scope :in_progress, -> { Order.complete }
  scope :in_delivery, -> { Order.in_delivery }
  scope :delivered, -> { Order.delivered }
  scope :canceled, -> { Order.canceled }

  enum status: { cart: 0, address: 1, fill_delivery: 2, payment: 3, confirm: 4, complete: 5,
                 in_delivery: 6, delivered: 7, canceled: 8 }

  aasm :status, enum: true do
    state :cart, initial: true
    state :address
    state :fill_delivery
    state :payment
    state :confirm
    state :complete
    state :in_delivery
    state :delivered
    state :canceled

    event :address do
      transitions from: :cart, to: :address
    end

    event :fill_delivery do
      transitions from: :address, to: :fill_delivery
    end

    event :payment do
      transitions from: :fill_delivery, to: :payment
    end

    event :confirm do
      transitions from: :payment, to: :confirm
    end

    event :complete do
      transitions from: :confirm, to: :complete
    end

    event :in_delivery do
      transitions from: :complete, to: :in_delivery
    end

    event :delivered do
      transitions from: :in_delivery, to: :delivered
    end

    event :canceled do
      transitions from: %i[complete in_delivery delivered], to: :canceled
    end
  end
end

app/models/review.rb
class Review < ApplicationRecord
  enum status: { unprocessed: 0, approved: 1, rejected: 2 }

  belongs_to :user
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :orders, dependent: nil
  has_many :addresses, as: :resource, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :confirmable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook]

  validate :password_complexity

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.skip_confirmation!
    end
  end

  def password_complexity
    return if password.blank? || password =~ /(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])/

    errors.add :password, I18n.t('validate.password_complexity')
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  include Pagy::Backend

  COUNT_PAGE_BOOKS = 12

  def index
    @sorted_books = SortingService.new(Book.all, params).call
    @books_presenter = BooksPresenter.new(params: params)
    @pagy, @books_category = pagy(@sorted_books, items: COUNT_PAGE_BOOKS)
  end

  def show
    @current_book = Book.find_by(id: params[:id])
    @review_presenter = ReviewPresenter.new(current_book: @current_book)
    @current_book_presenter = CurrentBookPresenter.new(current_book: @current_book)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def index
    @books_presenter = BooksPresenter.new(params: params)
    @cart_presenter = CartPresenter.new(current_order: current_order)
    @cart_books = current_order&.books
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @books_presenter = BooksPresenter.new(params: params)
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :authenticate_user!

  def new
    @presenter = AddressPresenter.new(current_user: current_user)
  end
end

app/helpers/books_helper.rb
module BooksHelper
  include Pagy::Frontend
end

app/helpers/checkout_helper.rb
module CheckoutHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def resource_class
    devise_mapping.to
  end
end

app/views/settings/_settings_account.html.haml
.row.mb-60
  .col-sm-5
    %p.in-gold-500.font-18.mb-25
      = t('settings.email')
    = form_tag settings_email_path(current_user), method: :put, class: 'general-form-md' do
      = hidden_field_tag :user_id, current_user.id
      .form-group.mb-35
        %label.control-label.input-label{for: "email"}= t('settings.enter_email')
        %input#email.form-control{name:"email", type: "email", placeholder: "Enter your email"}
      .general-text-align
        = submit_tag t('settings.save'), class: 'btn btn-default mb-35'
  .col-sm-5.col-sm-offset-1
    %p.in-gold-500.font-18.mb-25= t('settings.password')
    = form_tag account_path(current_user), method: :put, class: 'general-form-md divider-lg-bottom pb-25' do
      .form-group.mb-30
        %label.control-label.input-label{for: "oldPassword"}
          = t('settings.old_password')
        = text_field_tag "old_password", "", class: 'form-control', type: "password", id: 'oldPassword', placeholder: "Old Password"
      .form-group.mb-30
        %label.control-label.input-label{for: "password"}
          = t('settings.new_password')
        = text_field_tag "new_password", "", class: 'form-control', type: "password", id: 'password', placeholder: "New Password"
      .form-group.mb-40
        %label.control-label.input-label{for: "confirmPassword"}
          = t('settings.confirm_password')
        = text_field_tag "confirm_password", "", class: 'form-control', type: "password", id: 'confirmPassword', placeholder: "Confirm Password"
      .general-text-align
        = submit_tag t('settings.save'), class: 'btn btn-default mb-35'
  .col-sm-12
    %p.in-gold-500.font-18.mb-25= t('settings.remove_account')
    = form_tag account_path(current_user), method: :delete do
      .general-settings-btn
        %button.btn.disabled.mb-20= t('settings.remove_account_submit')
      .form-group.checkbox.general-settings-checkbox
        %label.checkbox-label
          %input.checkbox-input{type: "checkbox", hidden: "true"}
          %span.checkbox-icon
            %i.fa.fa-check
          %span.checkbox-text= t('settings.understand_user_detele')
          

app/views/settings/new.html.haml
%main.container
  %h1.general-title-margin
    = t('settings.title')
  %ul.nav.clearfix.mb-20{role: "tablist"}
    %li.tab-item.active{role: "presentation"}
      %a.tab-link{href: "#address", 'aria-controls': "address", role: "tab", 'data-toggle': "tab"}
        = t('settings.address')
    %li.tab-item{role: "presentation"}
      %a.tab-link{href: "#privacy", 'aria-controls': "privacy", role: "tab", 'data-toggle': "tab"}
        = t('settings.privacy')
  .tab-content
    #address.tab-pane.fade.in.active.general-main-wrap{role: "tabpanel"}
      .hidden-xs.hidden-sm
        .row
          .col-md-5
            %h3.general-subtitle.mt-0
              = t('settings.billing_address')
            = render partial: 'addresses/address_form', locals: {address_type: 'billing', address_form: @presenter.billing }
          .col-md-5.col-md-offset-1
            %h3.general-subtitle.mt-0
              = t('settings.shipping_address')
            = render partial: 'addresses/address_form', locals: {address_type: 'shipping', address_form: @presenter.shipping}
      .row
        .col-md-5.mb-40
          .visible-xs.visible-sm
            %h3.general-subtitle.mt-0
              = t('settings.billing_address')
            = render partial: 'addresses/address_form', locals: {address_type: 'billing', address_form: @presenter.billing }
        .col-md-5.col-md-offset-1.mb-25
          .visible-xs.visible-sm
            %h3.general-subtitle.mt-0
              = t('settings.shipping_address')
            = render partial: 'addresses/address_form', locals: {address_type: 'shipping', address_form: @presenter.shipping}
    #privacy.tab-pane.fade{role: "tabpanel"}
      = render partial: 'settings/settings_account'