config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", registrations: 'users/registrations' }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root 'home#index'

  resources :books
  resources :addresses
  resources :categories do
    resources :books, :index
  end
  resources :line_items
  resources :orders
  resources :reviews
  resources :settings
  resources :settings_emails
  resource :account
  resources :coupons
  resources :checkout, param: :step
  resources :carts, path: '/carts/line_items'
end

app/models/address.rb
class Address < ApplicationRecord
  enum address_type: { billing: 0, shipping: 1 }

  belongs_to :resource, polymorphic: true
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :book_authors, dependent: :destroy
  has_many :books, through: :book_authors, dependent: nil

  def full_name
    "#{first_name}' '#{last_name}"
  end
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :category
  has_many :book_authors, dependent: :destroy
  has_many :authors, through: :book_authors, dependent: nil
  has_many :reviews, dependent: :destroy
  has_many :line_items, dependent: :destroy
  has_many :book_images, dependent: :destroy
end

app/models/book_author.rb
class BookAuthor < ApplicationRecord
  belongs_to :book
  belongs_to :author
end

app/models/book_image.rb
class BookImage < ApplicationRecord
  include ImageUploader::Attachment(:image)
  enum image_type: { main: 0, additional: 1 }

  belongs_to :book, optional: true

  validate :main_image

  private

  def main_image
    return unless book
    return unless book.book_images.main.present? && image_type == 'main'

    errors.add :image_type, I18n.t('validate.main_image')
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :books, dependent: :destroy
end

app/models/coupon.rb
class Coupon < ApplicationRecord
  belongs_to :order, optional: true
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  belongs_to :order
end

app/models/delivery.rb
class Delivery < ApplicationRecord
  has_many :orders, dependent: :destroy
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :book
  belongs_to :order, optional: true
end

app/models/order.rb
class Order < ApplicationRecord
  include AASM

  belongs_to :delivery, optional: true
  belongs_to :user, optional: true
  has_many :line_items, dependent: :destroy
  has_many :books, through: :line_items
  has_many :addresses, as: :resource, dependent: :destroy
  has_one :credit_card, dependent: :destroy
  has_one :coupon, dependent: :nullify

  scope :in_progress, -> { Order.complete }
  scope :in_delivery, -> { Order.in_delivery }
  scope :delivered, -> { Order.delivered }
  scope :canceled, -> { Order.canceled }

  enum status: { cart: 0, address: 1, fill_delivery: 2, payment: 3, confirm: 4, complete: 5,
                 in_delivery: 6, delivered: 7, canceled: 8 }

  aasm :status, enum: true do
    state :cart, initial: true
    state :address
    state :fill_delivery
    state :payment
    state :confirm
    state :complete
    state :in_delivery
    state :delivered
    state :canceled

    event :address do
      transitions from: :cart, to: :address
    end

    event :fill_delivery do
      transitions from: :address, to: :fill_delivery
    end

    event :payment do
      transitions from: :fill_delivery, to: :payment
    end

    event :confirm do
      transitions from: :payment, to: :confirm
    end

    event :complete do
      transitions from: :confirm, to: :complete
    end

    event :in_delivery do
      transitions from: :complete, to: :in_delivery
    end

    event :delivered do
      transitions from: :in_delivery, to: :delivered
    end

    event :canceled do
      transitions from: %i[complete in_delivery delivered], to: :canceled
    end
  end
end

app/models/review.rb
class Review < ApplicationRecord
  enum status: { unprocessed: 0, approved: 1, rejected: 2 }

  belongs_to :user
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :orders, dependent: nil
  has_many :addresses, as: :resource, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :confirmable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook]

  validate :password_complexity

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.skip_confirmation!
    end
  end

  def password_complexity
    return if password.blank? || password =~ /(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])/

    errors.add :password, I18n.t('validate.password_complexity')
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  include Pagy::Backend

  COUNT_PAGE_BOOKS = 12

  def index
    @sorted_books = SortingService.new(Book.all, params).call
    @books_presenter = BooksPresenter.new(params: params)
    @pagy, @books_category = pagy(@sorted_books, items: COUNT_PAGE_BOOKS)
  end

  def show
    @current_book = Book.find_by(id: params[:id])
    @review_presenter = ReviewPresenter.new(current_book: @current_book)
    @current_book_presenter = CurrentBookPresenter.new(current_book: @current_book)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def index
    @books_presenter = BooksPresenter.new(params: params)
    @cart_presenter = CartPresenter.new(current_order: current_order)
    @cart_books = current_order&.books
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @books_presenter = BooksPresenter.new(params: params)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!

  def index
    @sort_orders = OrderSortingService.new(params, current_user).call
  end

  def show
    find_order = Order.find_by(id: params[:id])
    return redirect_to orders_path unless find_order

    @order = find_order.decorate
    @cart_presenter = CartPresenter.new(current_order: @order)
  end
end

app/helpers/books_helper.rb
module BooksHelper
  include Pagy::Frontend
end

app/helpers/checkout_helper.rb
module CheckoutHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def resource_class
    devise_mapping.to
  end
end

app/views/carts/index.html.haml
%main.container.general-main-wrap
  %h1.general-title-margin
    = t('cart.title_cart')
  - if @cart_presenter.current_order && !@cart_presenter.current_order.complete?
    .visible-xs
      = render partial: 'carts/books/books_for_phone'
    .hidden-xs
      %table.table.table-hover
        %tr.no-hover
          %th.col-pic.pl-0
            %span.in-grey-600
              = t('cart.pruduct')
          %th.col-title
          %th.col-price
            %span.in-grey-600
              = t('cart.price')
          %th.col-quantity
            %span.in-grey-600
              = t('cart.quantity')
          %th.col-total
            %span.in-grey-600
              = t('cart.subtotal')
          %th.col-close
        = render partial: 'carts/books/book_cart'
    .general-order-wrap
      .row
        .col-sm-4
          - if @cart_presenter.current_order && @cart_presenter.current_order.coupon
            %div.input-group.general-input-group
              = t('cart.coupon_used')
          - else
            = form_tag coupon_path(@cart_presenter.current_order), method: :put, class: 'input-group general-input-group' do
              %label.input-label
                = t('cart.enter_coupon_code')
              = text_field_tag :coupon, '', placeholder: "Enter Your Coupon Code ", class: 'form-control mb-30'
              %div
                = submit_tag t('cart.apply_coupon'), class: 'btn btn-primary mr-5 mb-15'
        .col-sm-8
          .res-mr-200.text-center.general-text-right
            %p.in-gold-500.font-18
              = t('cart.order_summary')
            %table.general-summary-table.general-summary-table-right.general-text-right
              %tr
                %td
                  %p.font-16
                    = t('cart.subtotal_order')
                %td
                  %p.font-16
                    = "€#{@cart_presenter.order_summary_price}"
              %tr
                %td
                  %p.font-16
                    = t('cart.coupon')
                %td
                  %p.font-16
                    = "€#{@cart_presenter.coupon_discount}"
              %tr
                %td
                  %strong.font-18
                    = t('cart.order_total')
                %td
                  %strong.font-18
                    = "€#{@cart_presenter.order_total_price_with_coupon}"
            %button.btn.btn-default.mb-20.visible-xs-inline-block
              = t('cart.checkout')
    - if user_signed_in?
      = link_to t('cart.checkout'), checkout_path(step: :address), class: 'btn btn-default w-190 mb-20 hidden-xs center-block'
    - else
      = link_to t('cart.checkout'), checkout_path(step: :quick_registrate), class: 'btn btn-default w-190 mb-20 hidden-xs center-block'
  - else
    %div.mb-30
    %h1.text-center
      = t('cart.empty_cart')
    %br
    = link_to t('cart.back_to_store'), root_path, class: 'btn btn-default w-190 mb-20 hidden-xs center-block'

app/views/home/_show_best_books.html.haml
- if !@books_presenter.top_books_each_category.empty?
  .mb-35
    %h3= t('home_page.best_sellers')
    .row
      - @books_presenter.top_books_each_category.each do |book|
        .col-sm-6.col-md-3
          .general-thumb-wrap
            .thumbnail.general-thumbnail
              %img.img-shadow.general-thumbnail-img{src: @books_presenter.main_image_or_default(book), alt: "design-book"}
              .thumb-hover
                .general-thumb-link-wrap
                  = link_to book_path(book), class: 'thumb-hover-link' do
                    %i.fa.fa-eye.thumb-icon{'aria-hidden': "true"}
                  = link_to line_items_path(line_item: {current_book: book.id}), method: :post, class: 'thumb-hover-link' do
                    %i.fa.fa-shopping-cart.thumb-icon
          .mb-35
            .clearfix
              %p.pull-right.font-16.in-gold-500= "€ #{book.price}"
              %p.title.mr-55= book.title
            %span.divider-sm
            %p.lead.small
              - book.authors.each do |author|
                = author.full_name
- else
  .mb-35
    %h3= t('home_page.not_have_best_sellers')

app/views/home/_slider_data.html.haml
#slider.carousel.slide{'data-ride': "carousel"}
  %ol.carousel-indicators
    %li.active{'data-target': "#slider", 'data-slide-to': "0"}
    %li{'data-target': "#slider", 'data-slide-to': "1"}
    %li{'data-target': "#slider", 'data-slide-to': "2"}
  .carousel-inner{role: "listbox"}
    - @books_presenter.new_books_slider.each_with_index do |book, index|
      .item{:class => "#{'active' if index == 0}"}
        .row
          .col-sm-5
            .general-img-wrap
              %img.img-shadow.general-thumbnail-img{src: @books_presenter.main_image_or_default(book), alt: "design-book"}
          .col-sm-7
            .mb-60
              %h1= link_to book.title, book_path(book)
              %p.lead= book.description
              %p.lead.small
                - book.authors.each do |author|
                  = author.full_name
              .general-align
                = link_to t('home_page.buy_now'), line_items_path(line_item: {current_book: book.id}), method: :post, class: 'btn btn-primary'
  %a.left.carousel-control{href: "#slider", role: "button", 'data-slide': "prev"}
    %span.icon-prev{'aria-hidden': "true"}
    %span.sr-only= t('home_page.previous')
  %a.right.carousel-control{href: "#slider", role: "button", 'data-slide': "next"}
    %span.icon-next{'aria-hidden': "true"}
    %span.sr-only= t('home_page.next')

app/views/home/index.html.haml
%main.container
  = render partial: 'home/slider_data'
.container
  .jumbotron.text-center.mb-0
    %h2.h1= t('home_page.welcome')
    .mb-res-50
      %p= t('home_page.about_books')
    = link_to t('home_page.get_started'), books_path, class: 'btn btn-default'
  = render partial: 'home/show_best_books'