config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", registrations: 'users/registrations' }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root 'home#index'

  resources :books
  resources :addresses
  resources :categories do
    resources :books, :index
  end
  resources :line_items
  resources :orders
  resources :reviews
  resources :settings
  resources :settings_emails
  resource :account
  resources :coupons
  resources :checkout, param: :step
  resources :carts, path: '/carts/line_items'
end

app/models/address.rb
class Address < ApplicationRecord
  enum address_type: { billing: 0, shipping: 1 }

  belongs_to :resource, polymorphic: true
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :book_authors, dependent: :destroy
  has_many :books, through: :book_authors, dependent: nil

  def full_name
    "#{first_name}' '#{last_name}"
  end
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :category
  has_many :book_authors, dependent: :destroy
  has_many :authors, through: :book_authors, dependent: nil
  has_many :reviews, dependent: :destroy
  has_many :line_items, dependent: :destroy
  has_many :book_images, dependent: :destroy
end

app/models/book_author.rb
class BookAuthor < ApplicationRecord
  belongs_to :book
  belongs_to :author
end

app/models/book_image.rb
class BookImage < ApplicationRecord
  include ImageUploader::Attachment(:image)
  enum image_type: { main: 0, additional: 1 }

  belongs_to :book, optional: true

  validate :main_image

  private

  def main_image
    return unless book
    return unless book.book_images.main.present? && image_type == 'main'

    errors.add :image_type, I18n.t('validate.main_image')
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :books, dependent: :destroy
end

app/models/coupon.rb
class Coupon < ApplicationRecord
  belongs_to :order, optional: true
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  belongs_to :order
end

app/models/delivery.rb
class Delivery < ApplicationRecord
  has_many :orders, dependent: :destroy
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :book
  belongs_to :order, optional: true
end

app/models/order.rb
class Order < ApplicationRecord
  include AASM

  belongs_to :delivery, optional: true
  belongs_to :user, optional: true
  has_many :line_items, dependent: :destroy
  has_many :books, through: :line_items
  has_many :addresses, as: :resource, dependent: :destroy
  has_one :credit_card, dependent: :destroy
  has_one :coupon, dependent: :nullify

  scope :in_progress, -> { Order.complete }
  scope :in_delivery, -> { Order.in_delivery }
  scope :delivered, -> { Order.delivered }
  scope :canceled, -> { Order.canceled }

  enum status: { cart: 0, address: 1, fill_delivery: 2, payment: 3, confirm: 4, complete: 5,
                 in_delivery: 6, delivered: 7, canceled: 8 }

  aasm :status, enum: true do
    state :cart, initial: true
    state :address
    state :fill_delivery
    state :payment
    state :confirm
    state :complete
    state :in_delivery
    state :delivered
    state :canceled

    event :address do
      transitions from: :cart, to: :address
    end

    event :fill_delivery do
      transitions from: :address, to: :fill_delivery
    end

    event :payment do
      transitions from: :fill_delivery, to: :payment
    end

    event :confirm do
      transitions from: :payment, to: :confirm
    end

    event :complete do
      transitions from: :confirm, to: :complete
    end

    event :in_delivery do
      transitions from: :complete, to: :in_delivery
    end

    event :delivered do
      transitions from: :in_delivery, to: :delivered
    end

    event :canceled do
      transitions from: %i[complete in_delivery delivered], to: :canceled
    end
  end
end

app/models/review.rb
class Review < ApplicationRecord
  enum status: { unprocessed: 0, approved: 1, rejected: 2 }

  belongs_to :user
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :orders, dependent: nil
  has_many :addresses, as: :resource, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :confirmable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook]

  validate :password_complexity

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.skip_confirmation!
    end
  end

  def password_complexity
    return if password.blank? || password =~ /(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])/

    errors.add :password, I18n.t('validate.password_complexity')
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def destroy
    if current_user&.destroy
      cookies.delete(:current_order_id)
      flash[:success] = I18n.t('controllers.deleted_account')
    else
      flash[:error] = I18n.t('controllers.error_deleted_account')
    end
    redirect_to root_path
  end

  def update
    change_password = ChangePasswordService.call(current_user, params)
    if change_password[:success]
      flash[:success] = I18n.t('controllers.changed_password')
    else
      flash[:error] = I18n.t('controllers.wrong_password')
    end
    bypass_sign_in(current_user)
    redirect_to new_setting_path
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  include Pagy::Backend

  COUNT_PAGE_BOOKS = 12

  def index
    @sorted_books = SortingService.new(Book.all, params).call
    @books_presenter = BooksPresenter.new(params: params)
    @pagy, @books_category = pagy(@sorted_books, items: COUNT_PAGE_BOOKS)
  end

  def show
    @current_book = Book.find_by(id: params[:id])
    @review_presenter = ReviewPresenter.new(current_book: @current_book)
    @current_book_presenter = CurrentBookPresenter.new(current_book: @current_book)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def index
    @books_presenter = BooksPresenter.new(params: params)
    @cart_presenter = CartPresenter.new(current_order: current_order)
    @cart_books = current_order&.books
  end
end

app/controllers/coupons_controller.rb
class CouponsController < ApplicationController
  def update
    @coupon = Coupon.find_by(key: params[:coupon])

    if validate?
      @coupon.update(order_id: params[:id])
    else
      flash[:error] = I18n.t('controllers.wrong_coupon')
    end

    redirect_to(carts_path)
  end

  private

  def validate?
    return unless @coupon

    @coupon.order_id.nil?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @books_presenter = BooksPresenter.new(params: params)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!

  def index
    @sort_orders = OrderSortingService.new(params, current_user).call
  end

  def show
    find_order = Order.find_by(id: params[:id])
    return redirect_to orders_path unless find_order

    @order = find_order.decorate
    @cart_presenter = CartPresenter.new(current_order: @order)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    authorize :review, :create?

    review_service = ReviewService.new(reviews_form_params)

    if review_service.call
      flash[:success] = t('book_page.review.success_add_comment')
    else
      flash[:error] = review_service.errors
    end
    redirect_to book_path(reviews_form_params[:current_book])
  end

  private

  def reviews_form_params
    params.permit(:title, :text_review, :rating, :current_user, :current_book)
  end
end

app/helpers/books_helper.rb
module BooksHelper
  include Pagy::Frontend
end

app/helpers/checkout_helper.rb
module CheckoutHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def resource_class
    devise_mapping.to
  end
end

app/views/books/reviews/_review_form.html.haml
.mb-80
  %h3
    = t('book_page.review.write_a_review')
  %p.general-info-text
    = t('book_page.review.score')
  = form_tag reviews_path, method: :post do
    .md15
      %fieldset.rating
        - (ReviewPresenter::COUNT_STARS).downto(ReviewPresenter::MIN_STARS).each do |star_num|
          %input{name: "rating", id: "star#{star_num}", type: "radio", value: "#{star_num}"}
          %label.full{for: "star#{star_num}"}
    = hidden_field_tag 'current_user', current_user.id
    = hidden_field_tag 'current_book', @current_book.id
    .row
      .col-md-8
        .mb-40
          .form-group
            %label.control-label.input-label.in-grey-600{for: "title"}
              = t('book_page.review.title')
            = text_field_tag "title", "", class: 'form-control'
          .form-group
            %label.control-label.input-label.in-grey-600{for: "review"}
              = t('book_page.review.review')
            = text_area_tag "text_review", "", class: 'form-control'
        .text-right
          = submit_tag t('book_page.review.post') , id: 'review', class: 'btn mb-20'
          

app/views/books/reviews/_users_reviews.html.haml
.mb-80
  %h3.in-gold-500.mb-25
    = t('book_page.review.reviews') 
    (
    = @review_presenter.quantity_reviews
    )
  - @review_presenter.all_reviews.each do |review|
    .general-message-wrap.divider-lg
      .clearfix
        %span.img-circle.logo-size.inlide-block.pull-left.logo-empty
          = review.user.email.first
        .ml-70
          %div
            .general-message-date.hidden-xs
              = review.created_at.to_date
            .max-300
              .general-message-verified.pull-right
                = @review_presenter.verified?(review)
              .general-message-name
                = review.user.email
          .mb-15
            - ReviewPresenter::COUNT_STARS.times do |star|
              %i.fa.fa-star{class: @review_presenter.check_star(star, review)}
          %h4
            = review.title
          %p
            = review.text_review

app/views/carts/books/_book_cart.html.haml
- @cart_books.order(:id).each do |book|
  %tr
    %td
      .general-img-wrap-table
        .thumbnail.general-thumbnail
          %img.cart-img-shado{src: @books_presenter.main_image_or_default(book), alt: "design-book"}
          .thumb-hover
            .general-thumb-link-wrap
              = link_to book_path(book), class: 'thumb-hover-link' do
                %i.fa.fa-eye.thumb-icon{'aria-hidden': "true"}
    %td
      %p.title
        = link_to book.title, book_path(book)
    %td
      %span.font-16.in-gold-500
        = "€#{book.price}"
    %td
      .input-group
        = link_to line_item_path(minus: true, id: @cart_presenter.current_lineitem(book)), method: :PUT, class: 'input-link' do
          %i.fa.fa-minus.line-heaght-40
        %input.form-control.quantity-input{type: "text", value: "#{@cart_presenter.count_same_books(book)}"}
        = link_to line_item_path(plus: true, id: @cart_presenter.current_lineitem(book)), method: :PUT, class: 'input-link' do
          %i.fa.fa-plus.line-heaght-40
    %td
      %span.font-16.in-gold-500
        = "€#{@cart_presenter.subtotal_prise_book(book)}"
    %td
      = form_tag line_item_path(book.id), method: :delete do
        = button_tag(type: "submit", class: 'close general-cart-close', 'aria-label': "Close") do
          %span{'aria-hidden': "true"} &times;

app/views/carts/books/_books_for_phone.html.haml
- @cart_books.order(:id).each do |book|
  .general-cart-item.divider-lg-bottom.mb-30
    = form_tag line_item_path(book.id), method: :delete do
      = button_tag(type: "submit", class: 'close general-cart-close', 'aria-label': "Close") do
        %span{'aria-hidden': "true"} &times;
    .general-img-wrap-table
      .thumbnail.general-thumbnail
        %img.cart-img-shadow{src: @books_presenter.main_image_or_default(book), alt: "design-book"}
        .thumb-hover
          .general-thumb-link-wrap
            = link_to book_path(book), class: 'thumb-hover-link' do
              %i.fa.fa-eye.thumb-icon{'aria-hidden': "true"}
    %p.title
      = link_to book.title, book_path(book)
    %table.table
      %tr
        %td
          %span.in-grey-600
            = t('cart.price')
        %td
          %span.font-16.in-gold-500
            = I18n.t('cart.current_price', price: book.price)
      %tr
        %td.vertical-middle
          %span.in-grey-600
            = t('cart.quantity')
        %td
          .input-group
            = link_to line_item_path(minus: true, id: @cart_presenter.current_lineitem(book)), method: :PUT, class: 'input-link' do
              %i.fa.fa-minus.line-heaght-40
            %input.form-control.quantity-input{type: "text", value: "#{@cart_presenter.count_same_books(book)}"}
            = link_to line_item_path(plus: true, id: @cart_presenter.current_lineitem(book)), method: :PUT, class: 'input-link' do
              %i.fa.fa-plus.line-heaght-40
      %tr
        %td
          %span.in-grey-600
            = t('cart.subtotal')
        %td
          %span.font-16.in-gold-500
            = @cart_presenter.subtotal_prise_book(book)